# Generated by Django 3.1.2 on 2020-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='offerings',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
