# Generated by Django 3.1.2 on 2020-10-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_build_offerings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Component',
        ),
    ]
