# Generated by Django 3.1.2 on 2020-10-12 21:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_delete_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='offerings',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
