# Generated by Django 3.1.2 on 2020-10-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_auto_20201012_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='offerings',
            field=models.JSONField(),
        ),
    ]
