# Generated by Django 3.1.2 on 2020-10-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0002_auto_20201001_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='url',
            field=models.URLField(default='lala'),
            preserve_default=False,
        ),
    ]
