# Generated by Django 3.1.2 on 2020-10-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0005_auto_20201002_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='name',
            field=models.CharField(default='name missing', max_length=100),
            preserve_default=False,
        ),
    ]
