# Generated by Django 3.1.2 on 2020-10-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0006_offering_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
