# Generated by Django 3.1.2 on 2020-10-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0007_auto_20201003_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
