# Generated by Django 3.1.2 on 2020-10-14 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0009_auto_20201013_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offering',
            options={},
        ),
    ]
