# Generated by Django 3.1.2 on 2020-10-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0010_auto_20201014_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_offerings', models.PositiveIntegerField()),
                ('new_offerings', models.PositiveIntegerField()),
            ],
        ),
    ]
