# Generated by Django 3.1.2 on 2021-05-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0012_auto_20210521_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
    ]
