# Generated by Django 3.1.2 on 2020-10-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuSocket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MotherboardFormFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PsuFormFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MotherboardChipset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('max_memory_speed', models.IntegerField()),
                ('cpu_socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_chipsets', to='components.cpusocket', to_field='code')),
                ('memory_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_chipsets', to='components.memorytype', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('ram_slots', models.IntegerField(default=4)),
                ('m2_slots', models.IntegerField(default=1)),
                ('chipset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboards', to='components.motherboardchipset', to_field='code')),
                ('motherboard_form_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboards', to='components.motherboardformfactor', to_field='code')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboards', to='components.vendor', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('motherboard_form_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='components.motherboardformfactor', to_field='code')),
                ('psu_form_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='components.psuformfactor', to_field='code')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='components.vendor', to_field='code')),
            ],
        ),
    ]
