# Generated by Django 3.1.2 on 2020-10-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20201002_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CpuCoolerSocketConnection',
        ),
    ]
