# Generated by Django 3.1.2 on 2020-10-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20201003_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='read_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='write_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
