# Generated by Django 3.1.2 on 2020-10-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_auto_20201003_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='boost_clock',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='core_clock',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='tdp',
        ),
    ]
