# Generated by Django 3.1.2 on 2020-10-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_auto_20201003_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='module_size',
            field=models.IntegerField(default=8),
        ),
    ]
