# Generated by Django 3.1.2 on 2020-10-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_memory_module_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='module_size',
        ),
        migrations.AddField(
            model_name='memory',
            name='size',
            field=models.IntegerField(default=8),
        ),
    ]
