# Generated by Django 3.1.2 on 2020-10-10 23:52

import builder.utils
import builder.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20201010_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hdd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('format', models.TextField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=builder.utils.handle_upload, validators=[builder.validators.validate_image_extension])),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hdds', to='components.vendor', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='Ssd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('read_speed', models.IntegerField(blank=True, null=True)),
                ('write_speed', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=builder.utils.handle_upload, validators=[builder.validators.validate_image_extension])),
            ],
        ),
        migrations.RenameModel(
            old_name='StorageType',
            new_name='SsdType',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.AddField(
            model_name='ssd',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssds', to='components.ssdtype', to_field='code'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssds', to='components.vendor', to_field='code'),
        ),
    ]
