# Generated by Django 3.1.2 on 2020-10-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_auto_20201011_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdd',
            name='format',
            field=models.CharField(choices=[('3.5"', '3.5"'), ('2.5"', '2.5"')], default=('3.5"', '3.5"'), max_length=20),
        ),
    ]
