# Generated by Django 3.1.2 on 2020-10-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_auto_20201011_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpusocket',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='gputype',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='gpuvendor',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='memorytype',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='motherboardformfactor',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='psuformfactor',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='ssdtype',
            options={'ordering': ('code',)},
        ),
    ]
