# Generated by Django 3.1.2 on 2020-10-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0015_auto_20201013_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='psu',
            name='rating',
            field=models.CharField(choices=[('none', ''), ('white', '80 Plus'), ('bronze', '80 Plus Bronze'), ('silver', '80 Plus Silver'), ('gold', '80 Plus Gold'), ('platinum', '80 Plus Platinum'), ('titanium', '80 Plus Titanium')], default=('none', ''), max_length=20),
        ),
    ]
