# Generated by Django 3.1.2 on 2020-10-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0017_auto_20201014_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psu',
            name='rating',
            field=models.CharField(blank=True, choices=[('none', None), ('white', '80 Plus'), ('bronze', '80 Plus Bronze'), ('silver', '80 Plus Silver'), ('gold', '80 Plus Gold'), ('platinum', '80 Plus Platinum'), ('titanium', '80 Plus Titanium')], max_length=20, null=True),
        ),
    ]
