# Generated by Django 3.1.2 on 2020-10-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0019_auto_20201014_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psu',
            name='rating',
            field=models.CharField(blank=True, choices=[('80 Plus', '80 Plus'), ('80 Plus Bronze', '80 Plus Bronze'), ('80 Plus Silver', '80 Plus Silver'), ('80 Plus Gold', '80 Plus Gold'), ('80 Plus Platinum', '80 Plus Platinum'), ('80 Plus Titanium', '80 Plus Titanium')], max_length=20, null=True),
        ),
    ]
