# Generated by Django 3.1.2 on 2020-10-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0020_auto_20201014_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboardchipset',
            name='max_memory_frequency',
        ),
    ]
