# Generated by Django 3.1.2 on 2021-05-23 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0023_auto_20210523_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpusocket',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='gputype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='gpuvendor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='memorytype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='motherboardchipset',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='motherboardformfactor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='psuformfactor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='ssdtype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('name',)},
        ),
    ]
