# Generated by Django 3.1.2 on 2021-05-27 21:16

import builder.utils
import builder.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0024_auto_20210523_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorPanel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('panel', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'ordering': ('panel',),
            },
        ),
        migrations.CreateModel(
            name='MonitorResolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'ordering': ('resolution',),
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('size', models.FloatField()),
                ('refresh_rate', models.IntegerField()),
                ('curved', models.BooleanField(default=False)),
                ('gsync', models.CharField(blank=True, choices=[('G-Sync', 'G-Sync'), ('G-Sync Ultimate', 'G-Sync Ultimate'), ('G-Sync Compatible', 'G-Sync Compatible')], max_length=30, null=True)),
                ('freesync', models.CharField(blank=True, choices=[('FreeSync', 'FreeSync'), ('FreeSync Premium', 'FreeSync Premium'), ('FreeSync Premium Pro', 'FreeSync Premium Pro')], max_length=30, null=True)),
                ('image', models.ImageField(upload_to=builder.utils.handle_upload, validators=[builder.validators.validate_image_extension])),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='components.monitorpanel', to_field='panel')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='components.monitorresolution', to_field='resolution')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='components.vendor', to_field='code')),
            ],
        ),
    ]
